name: Basic Stock Info

on:
  schedule:
    - cron: '0 0 1 * *'  # 每月1日0點運行

  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: 安裝 Playwright 系統相依套件
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnspr4 \
            libnss3 \
            libasound2t64 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libcups2 \
            libdrm2 \
            libdbus-1-3 \
            libxkbcommon0 \
            libxcomposite1 \
            libxdamage1 \
            libxfixes3 \
            libxrandr2 \
            libgbm1 \
            libpango-1.0-0 \
            libcairo2

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt
          python -m playwright install --with-deps

      - name: execute py script
        run: |
          python python/basic_stock_info.py
            
      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull origin main  # Pull the latest changes
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Basic Stock Info" --allow-empty)
          git push origin main  # Push the changes
            
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: main