name: Institutional Investors Exchange

on:
  schedule:
    - cron: '0 15 * * 1-5'  # 每週一到週五下午3點運行
      timezone: 'Asia/Taipei'  # 指定時區為台北時間
      
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt

      - name: execute py script
        run: |
          python python/step0_institution_iInvestors.py
            
      - name: commit files
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add -A
            git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
            
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: main 